# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2
project_name: apps-workloads-private-event-v2alpha-event-multiplexer

variables:
  path_to_repo_root: "../../../../../../"
  path_to_project: "apps/workloads/private/event/v2alpha/event-multiplexer"
  project_name: "event-multiplexer"

dist: ./dist/apps/workloads/private/event/v2alpha/event-multiplexer/release

monorepo:
  tag_prefix: "apps-workloads-private-event-v2alpha-event-multiplexer/"
  dir: apps/workloads/private/event/v2alpha/event-multiplexer

includes:
  - from_file:
      path: ./.config/goreleaser/goreleaser.workload.yaml
#  - from_file:
#      path: ./.config/goreleaser/notarize.yaml
#  - from_file:
#      path: ./.config/goreleaser/dockerize.yaml

nightly:
  version_template: "{{ incpatch .Version }}-devel"
  tag_name: "apps-workloads-private-event-v2alpha-event-multiplexer/devel"
  publish_release: true
  keep_single_release: true

kos:
  - repositories:
      - ghcr.io/openecosystems/event-multiplexer
      #- openecosystems/event-multiplexer
    tags:
      - "{{.Version}}"
      - "{{.Tag}}"
      - latest
      - "{{if not .Prerelease}}stable{{end}}"
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64
      - darwin/amd64
      - darwin/arm64
      - windows/amd64
      - windows/arm64
