# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["engineering@jeannotcompany.com"]
description = "Platform Edge Router"
language = "rust"
manifest_version = 3
name = "communication-edge-router"
service_id = "P7ph3LOR6cyc47YRegHpM0"

#[scripts]
#  #post_build = "cp -R bin/ ../../../../../../dist/apps/workloads/internal/edge/v2alpha/edge-router/bin && cp -R pkg/ ../../../../../../dist/apps/workloads/internal/edge/v2alpha/edge-router/pkg"
#  post_build = "cp -R bin/ ../../../../../../dist/apps/workloads/internal/edge/v2alpha/edge-router/bin"

[local_server]

  [local_server.config_stores]
    [local_server.config_stores.context_localhost]
      format = "inline-toml"
    [local_server.config_stores.context_localhost.contents]
      #"context" = "localhost;local-2;6477;communication"
      "context" = "oeco.cloud;local-2;6477;nosystem"
    [local_server.config_stores.routes_localhost]
      format = "inline-toml"
    [local_server.config_stores.routes_localhost.contents]
      "12345678" = "na-us-1;organization123;workspace123"
      "23456789" = "na-us-1;health-organization;wecare_local"
      "34567890" = "na-us-1;platform;dimy"
      "45678901" = "na-us-1;platform;ricky"
      "56789012" = "na-us-1;platform;patrick"
      "67890123" = "gov-us-1;gov-agency;workspace-gov"
      "incorrect" = "gov-us-1"

  [local_server.geolocation]
    format = "inline-toml"
    [local_server.geolocation.addresses]
      [local_server.geolocation.addresses."127.0.0.1"]
        as_name = "Jeannot & Company"
        city = "Atlanta"
        as_number = 12345
        area_code = 123
        conn_speed = "broadband"
        conn_type = "wired"
        continent = "NA"
        country_code = "US"
        country_code3 = "USA"
        country_name = "United States"
        latitude = 12.345
        longitude = 54.321
        metro_code = 0
        postal_code = "30024"
        proxy_description = "?"
        proxy_type = "?"
        region = "US-GA"
        utc_offset = -700