# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2
project_name: apps-workloads-public-ecosystem-v2alpha-ecosystem

variables:
  path_to_repo_root: "../../../../../../"
  path_to_project: "apps/workloads/public/ecosystem/v2alpha/ecosystem"
  project_name: "ecosystem"

dist: ./dist/apps/workloads/public/ecosystem/v2alpha/ecosystem/release

monorepo:
  tag_prefix: "apps-workloads-public-ecosystem-v2alpha-ecosystem/"
  dir: apps/workloads/public/ecosystem/v2alpha/ecosystem

includes:
  - from_file:
      path: ./.config/goreleaser/goreleaser.workload.yaml
#  - from_file:
#      path: ./.config/goreleaser/notarize.yaml
#  - from_file:
#      path: ./.config/goreleaser/dockerize.yaml

nightly:
  version_template: "{{ incpatch .Version }}-devel"
  tag_name: "apps-workloads-public-ecosystem-v2alpha-ecosystem/devel"
  publish_release: true
  keep_single_release: true

kos:
  - repositories:
      - ghcr.io/openecosystems/ecosystem
      #- openecosystems/ecosystem
    tags:
      - "{{.Version}}"
      - "{{.Tag}}"
      - latest
      - "{{if not .Prerelease}}stable{{end}}"
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64
      - darwin/amd64
      - darwin/arm64
      - windows/amd64
      - windows/arm64
