# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2
project_name: lighthouse-v2alpha

variables:
  path_to_repo_root: "../../../../../../"
  path_to_project: "apps/workloads/public/mesh/v2alpha/lighthouse"
  project_name: "lighthouse"

dist: ./dist/apps/workloads/public/mesh/v2alpha/lighthouse/release

monorepo:
  tag_prefix: "lighthouse-v2alpha/"
  dir: apps/workloads/public/mesh/v2alpha/lighthouse

includes:
  - from_file:
      path: ./.config/goreleaser/goreleaser.workload.yaml
#  - from_file:
#      path: ./.config/goreleaser/notarize.yaml
#  - from_file:
#      path: ./.config/goreleaser/dockerize.yaml

nightly:
  version_template: "{{ incpatch .Version }}-devel"
  tag_name: "lighthouse-v2alpha/devel"
  publish_release: true
  keep_single_release: true


kos:
  - repositories:
      - ghcr.io/openecosystems/lighthouse
      #- openecosystems/lighthouse
    tags:
      - "{{.Version}}"
      - "{{.Tag}}"
      - latest
      - "{{if not .Prerelease}}stable{{end}}"
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64
      - darwin/amd64
      - darwin/arm64
      - windows/amd64
      - windows/arm64
