# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2
project_name: oeco-sdk-v2beta

variables:
    path_to_repo_root: '../../'
    path_to_project: 'go/oeco-sdk/v2beta'
    project_name: 'oeco-sdk-v2beta'

dist: ./dist/go/oeco-sdk/v2beta

monorepo:
    tag_prefix: 'go/oeco-sdk/v2beta/'
    dir: go/oeco-sdk/v2beta

includes:
    - from_file:
          path: ./.config/goreleaser/goreleaser.sdk.yaml
    - from_file:
          path: ./.config/goreleaser/notarize.yaml

nightly:
    version_template: '{{ incpatch .Version }}-devel'
    tag_name: 'go/oeco-sdk/v2beta/devel'
    publish_release: true
    keep_single_release: true
    #
