# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2
project_name: apps-clients-public-cli-v2alpha-oeco

variables:
  path_to_repo_root: "../../../../../../"
  path_to_project: "apps/clients/public/cli/v2alpha/oeco"

dist: ./dist/apps/clients/public/cli/v2alpha/oeco

monorepo:
  tag_prefix: "apps-clients-public-cli-v2alpha-oeco/"
  dir: apps/clients/public/cli/v2alpha/oeco

includes:
  - from_file:
      path: ./.config/goreleaser/goreleaser.cli.yaml
#  - from_file:
#      path: ./.config/goreleaser/notarize.yaml

nightly:
  version_template: "{{ incpatch .Version }}-devel"
  tag_name: "oeco/devel"
  publish_release: true
  keep_single_release: true