name: build

on: [push, pull_request]
permissions:
  contents: write
  pull-requests: write
jobs:
  build:
    strategy:
      matrix:
        #go_version: ["1.19", stable]
        go_version: [stable]
    uses: ./.github/workflows/_build.yml
    with:
      go_version: ${{ matrix.go_version }}
